<?php
$adminpath = array (
  'block.role.php' => 2,
  'function.finder.php' => 2,
  'modifier.barcode.php' => 2,
  'function.json.php' => 2,
  'function.tag.php' => 2,
  'block.tab.php' => 2,
  'function.uploader.php' => 2,
  'block.area.php' => 2,
  'function.template_filter.php' => 2,
  'modifier.size.php' => 2,
  'function.filter.php' => 2,
  'compiler.finder.php' => 2,
  'modifier.region.php' => 2,
  'compiler.button.php' => 2,
  'function.toinput.php' => 2,
  'function.refer.php' => 2,
  'block.tabber.php' => 2,
  'function.pager.php' => 2,
  'input.object.php' => 2,
  'function.setting.php' => 2,
  'compiler.finder_lister.php' => 2,
  'block.help.php' => 2,
  'modifier.b2bcur.php' => 2,
  'compiler.img.php' => 2,
);